### ISSUE TITLE
converter_pix stopped working, any help?

### ISSUE THREAD

**Issue by oCCFANo** [mwl4/ConverterPIX#36]
It happens when I try to convert ATS 1.38 extracted files.

Tried several times and it always stopped at 76%. It is located at ATS **prefab** folder, the file is _sidewalk_fork_2-1-2_country_2-2_country_4m_tmpl_r_.

See the screenshot here: https://s1.ax1x.com/2020/07/15/UaT02V.png

**Comment by mwl4** [comment]
Fixed.

**Comment by umustbeloggedintododat** [comment]
This answer "fixed" is too vague. The problem still persists and at 33% (Jazzycat's AI Traffic Pack) it crashes.
